//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicepagos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    public partial class Factura : object
    {
        
        private int IdField;
        
        private string EmpresaField;
        
        private string NroFacturaField;
        
        private string CIField;
        
        private string NombreCompletoField;
        
        private string PeriodoField;
        
        private decimal MontoField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NroFactura
        {
            get
            {
                return this.NroFacturaField;
            }
            set
            {
                this.NroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CI
        {
            get
            {
                return this.CIField;
            }
            set
            {
                this.CIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NombreCompleto
        {
            get
            {
                return this.NombreCompletoField;
            }
            set
            {
                this.NombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Periodo
        {
            get
            {
                return this.PeriodoField;
            }
            set
            {
                this.PeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicepagos.WebpagosSoap")]
    public interface WebpagosSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarDeudas", ReplyAction="*")]
        Servicepagos.ConsultarDeudasResponse ConsultarDeudas(Servicepagos.ConsultarDeudasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarDeudas", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicepagos.ConsultarDeudasResponse> ConsultarDeudasAsync(Servicepagos.ConsultarDeudasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento facturas del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        Servicepagos.PagarResponse Pagar(Servicepagos.PagarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicepagos.PagarResponse> PagarAsync(Servicepagos.PagarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDeudasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDeudas", Namespace="http://tempuri.org/", Order=0)]
        public Servicepagos.ConsultarDeudasRequestBody Body;
        
        public ConsultarDeudasRequest()
        {
        }
        
        public ConsultarDeudasRequest(Servicepagos.ConsultarDeudasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarDeudasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ConsultarDeudasRequestBody()
        {
        }
        
        public ConsultarDeudasRequestBody(string ci)
        {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDeudasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDeudasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Servicepagos.ConsultarDeudasResponseBody Body;
        
        public ConsultarDeudasResponse()
        {
        }
        
        public ConsultarDeudasResponse(Servicepagos.ConsultarDeudasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarDeudasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Servicepagos.Factura[] ConsultarDeudasResult;
        
        public ConsultarDeudasResponseBody()
        {
        }
        
        public ConsultarDeudasResponseBody(Servicepagos.Factura[] ConsultarDeudasResult)
        {
            this.ConsultarDeudasResult = ConsultarDeudasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pagar", Namespace="http://tempuri.org/", Order=0)]
        public Servicepagos.PagarRequestBody Body;
        
        public PagarRequest()
        {
        }
        
        public PagarRequest(Servicepagos.PagarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Servicepagos.Factura[] facturas;
        
        public PagarRequestBody()
        {
        }
        
        public PagarRequestBody(Servicepagos.Factura[] facturas)
        {
            this.facturas = facturas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Servicepagos.PagarResponseBody Body;
        
        public PagarResponse()
        {
        }
        
        public PagarResponse(Servicepagos.PagarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PagarResult;
        
        public PagarResponseBody()
        {
        }
        
        public PagarResponseBody(bool PagarResult)
        {
            this.PagarResult = PagarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebpagosSoapChannel : Servicepagos.WebpagosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebpagosSoapClient : System.ServiceModel.ClientBase<Servicepagos.WebpagosSoap>, Servicepagos.WebpagosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebpagosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebpagosSoapClient.GetBindingForEndpoint(endpointConfiguration), WebpagosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebpagosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebpagosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebpagosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebpagosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebpagosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicepagos.ConsultarDeudasResponse Servicepagos.WebpagosSoap.ConsultarDeudas(Servicepagos.ConsultarDeudasRequest request)
        {
            return base.Channel.ConsultarDeudas(request);
        }
        
        public Servicepagos.Factura[] ConsultarDeudas(string ci)
        {
            Servicepagos.ConsultarDeudasRequest inValue = new Servicepagos.ConsultarDeudasRequest();
            inValue.Body = new Servicepagos.ConsultarDeudasRequestBody();
            inValue.Body.ci = ci;
            Servicepagos.ConsultarDeudasResponse retVal = ((Servicepagos.WebpagosSoap)(this)).ConsultarDeudas(inValue);
            return retVal.Body.ConsultarDeudasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicepagos.ConsultarDeudasResponse> Servicepagos.WebpagosSoap.ConsultarDeudasAsync(Servicepagos.ConsultarDeudasRequest request)
        {
            return base.Channel.ConsultarDeudasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicepagos.ConsultarDeudasResponse> ConsultarDeudasAsync(string ci)
        {
            Servicepagos.ConsultarDeudasRequest inValue = new Servicepagos.ConsultarDeudasRequest();
            inValue.Body = new Servicepagos.ConsultarDeudasRequestBody();
            inValue.Body.ci = ci;
            return ((Servicepagos.WebpagosSoap)(this)).ConsultarDeudasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicepagos.PagarResponse Servicepagos.WebpagosSoap.Pagar(Servicepagos.PagarRequest request)
        {
            return base.Channel.Pagar(request);
        }
        
        public bool Pagar(Servicepagos.Factura[] facturas)
        {
            Servicepagos.PagarRequest inValue = new Servicepagos.PagarRequest();
            inValue.Body = new Servicepagos.PagarRequestBody();
            inValue.Body.facturas = facturas;
            Servicepagos.PagarResponse retVal = ((Servicepagos.WebpagosSoap)(this)).Pagar(inValue);
            return retVal.Body.PagarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicepagos.PagarResponse> Servicepagos.WebpagosSoap.PagarAsync(Servicepagos.PagarRequest request)
        {
            return base.Channel.PagarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicepagos.PagarResponse> PagarAsync(Servicepagos.Factura[] facturas)
        {
            Servicepagos.PagarRequest inValue = new Servicepagos.PagarRequest();
            inValue.Body = new Servicepagos.PagarRequestBody();
            inValue.Body.facturas = facturas;
            return ((Servicepagos.WebpagosSoap)(this)).PagarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebpagosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebpagosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebpagosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56986/Webpagos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebpagosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56986/Webpagos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebpagosSoap,
            
            WebpagosSoap12,
        }
    }
}
