//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sPersona
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private int ciField;
        
        private string nombreField;
        
        private string pApellidoField;
        
        private string sApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ci
        {
            get
            {
                return this.ciField;
            }
            set
            {
                this.ciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pApellido
        {
            get
            {
                return this.pApellidoField;
            }
            set
            {
                this.pApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sApellido
        {
            get
            {
                return this.sApellidoField;
            }
            set
            {
                this.sApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sPersona.wsPersonaSoap")]
    public interface wsPersonaSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/persona", ReplyAction="*")]
        sPersona.personaResponse persona(sPersona.personaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/persona", ReplyAction="*")]
        System.Threading.Tasks.Task<sPersona.personaResponse> personaAsync(sPersona.personaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaPersonaResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaPersona", ReplyAction="*")]
        sPersona.ListaPersonaResponse ListaPersona(sPersona.ListaPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<sPersona.ListaPersonaResponse> ListaPersonaAsync(sPersona.ListaPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarPersona", ReplyAction="*")]
        sPersona.EditarPersonaResponse EditarPersona(sPersona.EditarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<sPersona.EditarPersonaResponse> EditarPersonaAsync(sPersona.EditarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        bool EliminarPersona(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarPersonaAsync(int ci);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class personaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="persona", Namespace="http://tempuri.org/", Order=0)]
        public sPersona.personaRequestBody Body;
        
        public personaRequest()
        {
        }
        
        public personaRequest(sPersona.personaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class personaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sapelldo;
        
        public personaRequestBody()
        {
        }
        
        public personaRequestBody(int ci, string nombre, string pApellido, string sapelldo)
        {
            this.ci = ci;
            this.nombre = nombre;
            this.pApellido = pApellido;
            this.sapelldo = sapelldo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class personaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="personaResponse", Namespace="http://tempuri.org/", Order=0)]
        public sPersona.personaResponseBody Body;
        
        public personaResponse()
        {
        }
        
        public personaResponse(sPersona.personaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class personaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sPersona.Persona personaResult;
        
        public personaResponseBody()
        {
        }
        
        public personaResponseBody(sPersona.Persona personaResult)
        {
            this.personaResult = personaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaPersona", Namespace="http://tempuri.org/", Order=0)]
        public sPersona.ListaPersonaRequestBody Body;
        
        public ListaPersonaRequest()
        {
        }
        
        public ListaPersonaRequest(sPersona.ListaPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaPersonaRequestBody
    {
        
        public ListaPersonaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public sPersona.ListaPersonaResponseBody Body;
        
        public ListaPersonaResponse()
        {
        }
        
        public ListaPersonaResponse(sPersona.ListaPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sPersona.Persona[] ListaPersonaResult;
        
        public ListaPersonaResponseBody()
        {
        }
        
        public ListaPersonaResponseBody(sPersona.Persona[] ListaPersonaResult)
        {
            this.ListaPersonaResult = ListaPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarPersona", Namespace="http://tempuri.org/", Order=0)]
        public sPersona.EditarPersonaRequestBody Body;
        
        public EditarPersonaRequest()
        {
        }
        
        public EditarPersonaRequest(sPersona.EditarPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sApellido;
        
        public EditarPersonaRequestBody()
        {
        }
        
        public EditarPersonaRequestBody(int ci, string nombre, string pApellido, string sApellido)
        {
            this.ci = ci;
            this.nombre = nombre;
            this.pApellido = pApellido;
            this.sApellido = sApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public sPersona.EditarPersonaResponseBody Body;
        
        public EditarPersonaResponse()
        {
        }
        
        public EditarPersonaResponse(sPersona.EditarPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditarPersonaResult;
        
        public EditarPersonaResponseBody()
        {
        }
        
        public EditarPersonaResponseBody(bool EditarPersonaResult)
        {
            this.EditarPersonaResult = EditarPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsPersonaSoapChannel : sPersona.wsPersonaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsPersonaSoapClient : System.ServiceModel.ClientBase<sPersona.wsPersonaSoap>, sPersona.wsPersonaSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), wsPersonaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sPersona.personaResponse sPersona.wsPersonaSoap.persona(sPersona.personaRequest request)
        {
            return base.Channel.persona(request);
        }
        
        public sPersona.Persona persona(int ci, string nombre, string pApellido, string sapelldo)
        {
            sPersona.personaRequest inValue = new sPersona.personaRequest();
            inValue.Body = new sPersona.personaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombre = nombre;
            inValue.Body.pApellido = pApellido;
            inValue.Body.sapelldo = sapelldo;
            sPersona.personaResponse retVal = ((sPersona.wsPersonaSoap)(this)).persona(inValue);
            return retVal.Body.personaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sPersona.personaResponse> sPersona.wsPersonaSoap.personaAsync(sPersona.personaRequest request)
        {
            return base.Channel.personaAsync(request);
        }
        
        public System.Threading.Tasks.Task<sPersona.personaResponse> personaAsync(int ci, string nombre, string pApellido, string sapelldo)
        {
            sPersona.personaRequest inValue = new sPersona.personaRequest();
            inValue.Body = new sPersona.personaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombre = nombre;
            inValue.Body.pApellido = pApellido;
            inValue.Body.sapelldo = sapelldo;
            return ((sPersona.wsPersonaSoap)(this)).personaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sPersona.ListaPersonaResponse sPersona.wsPersonaSoap.ListaPersona(sPersona.ListaPersonaRequest request)
        {
            return base.Channel.ListaPersona(request);
        }
        
        public sPersona.Persona[] ListaPersona()
        {
            sPersona.ListaPersonaRequest inValue = new sPersona.ListaPersonaRequest();
            inValue.Body = new sPersona.ListaPersonaRequestBody();
            sPersona.ListaPersonaResponse retVal = ((sPersona.wsPersonaSoap)(this)).ListaPersona(inValue);
            return retVal.Body.ListaPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sPersona.ListaPersonaResponse> sPersona.wsPersonaSoap.ListaPersonaAsync(sPersona.ListaPersonaRequest request)
        {
            return base.Channel.ListaPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<sPersona.ListaPersonaResponse> ListaPersonaAsync()
        {
            sPersona.ListaPersonaRequest inValue = new sPersona.ListaPersonaRequest();
            inValue.Body = new sPersona.ListaPersonaRequestBody();
            return ((sPersona.wsPersonaSoap)(this)).ListaPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sPersona.EditarPersonaResponse sPersona.wsPersonaSoap.EditarPersona(sPersona.EditarPersonaRequest request)
        {
            return base.Channel.EditarPersona(request);
        }
        
        public bool EditarPersona(int ci, string nombre, string pApellido, string sApellido)
        {
            sPersona.EditarPersonaRequest inValue = new sPersona.EditarPersonaRequest();
            inValue.Body = new sPersona.EditarPersonaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombre = nombre;
            inValue.Body.pApellido = pApellido;
            inValue.Body.sApellido = sApellido;
            sPersona.EditarPersonaResponse retVal = ((sPersona.wsPersonaSoap)(this)).EditarPersona(inValue);
            return retVal.Body.EditarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sPersona.EditarPersonaResponse> sPersona.wsPersonaSoap.EditarPersonaAsync(sPersona.EditarPersonaRequest request)
        {
            return base.Channel.EditarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<sPersona.EditarPersonaResponse> EditarPersonaAsync(int ci, string nombre, string pApellido, string sApellido)
        {
            sPersona.EditarPersonaRequest inValue = new sPersona.EditarPersonaRequest();
            inValue.Body = new sPersona.EditarPersonaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombre = nombre;
            inValue.Body.pApellido = pApellido;
            inValue.Body.sApellido = sApellido;
            return ((sPersona.wsPersonaSoap)(this)).EditarPersonaAsync(inValue);
        }
        
        public bool EliminarPersona(int ci)
        {
            return base.Channel.EliminarPersona(ci);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPersonaAsync(int ci)
        {
            return base.Channel.EliminarPersonaAsync(ci);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64445/wsPersona.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64445/wsPersona.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsPersonaSoap,
            
            wsPersonaSoap12,
        }
    }
}
